name: release_actions

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Zip
        env:
          TZ: 'Asia/Tokyo'
        run: |
          zip -r labmeeting-memo-template *
          echo "::set-env name=release_tag::v$(date '+%Y%m%d_%H%M')"
          
      - uses: actions/create-release@master
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release
          release_name: release
          body: |
            最新版${{ env.release_tag }}のダウンロードはこちらから．
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./labmeeting-memo-template.zip
          asset_name: labmeeting-memo-template.zip
          asset_content_type: application/zip



